### ISSUE TITLE
LoadPackage and Streaming

### ISSUE THREAD

**Issue by bascyr** [dbzhang800/QtXlsxWriter#182]
Hi,
I'd like to shiow with a QProgressBar the loading state of a file xls.

I suppose that all streams happen when the file is fixed in the Document constructor.

QXlsx::Document xfile(c:/"test.xls");

Which method inside xlsdocument.cpp can be useful?

Thanks.
Cyrille

**Comment by VSRonin** [comment]
As the operation of loading the the document is totally synchronous there's no feature to provide feedback support. Best thing is to show an undefined progress bar as described in http://doc.qt.io/qt-5/qprogressbar.html

If minimum and maximum both are set to 0, the bar shows a busy indicator instead of a percentage of steps. This is useful, for example, when using QNetworkAccessManager to download items when they are unable to determine the size of the item being downloaded.

**Comment by bascyr** [comment]
Thanks for answer.
